
--what is the total revenue by month


SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_January_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_February_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_March_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_April_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_May_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_June_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_July_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_August_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_September_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_October_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_November_2019
GROUP BY MONTH
UNION ALL
SELECT month,
ROUND(SUM(Quantity_Ordered* Price_Each), 2) AS TOTAL_REVENUE
FROM Sales_December_2019
GROUP BY MONTH;
 


--WHAT IS THE TOTAL NUMBER OF ORDER BY MONTH



SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_January_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_February_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_March_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_April_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_May_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_June_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_July_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_August_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_September_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_October_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_November_2019
GROUP BY MONTH
UNION ALL
SELECT month,
COUNT(DISTINCT Order_ID) TOTAL_NO_ORDER
FROM Sales_December_2019
GROUP BY MONTH;



--WHAT IS THE BEST-SELLING PRODUCT/PRODUCT WITH THE HIGHEST REVENUE


SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_January_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_February_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_March_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_April_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_May_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_June_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_July_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_August_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_September_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_October_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_November_2019
GROUP BY Product,MONTH
UNION ALL
SELECT DISTINCT PRODUCT,MONTH,
SUM(Quantity_Ordered* Price_Each) AS TOTAL_REVENUE
FROM Sales_December_2019
GROUP BY Product,MONTH
ORDER BY TOTAL_REVENUE DESC;
 

 -- WHAT IS THE TOTAL REVENUE BY CITY

 SELECT DISTINCT CITY
 FROM Sales_January_2019;


WITH MONTHLY_SALES AS (
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_January_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_February_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_March_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_April_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_May_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_June_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_July_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_August_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each 
FROM Sales_September_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_October_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_November_2019
UNION ALL
SELECT MONTH,CITY,Quantity_Ordered,Price_Each
FROM Sales_December_2019
)
SELECT  MONTH,ROUND(SUM(CASE WHEN CITY = 'San Francisco' THEN (Quantity_Ordered * Price_Each)END), 2) AS SAN_FRANCISCO,
              ROUND(SUM(CASE WHEN CITY = 'Portland' THEN (Quantity_Ordered * Price_Each)END), 2) AS PORTLAND,
              ROUND(SUM(CASE WHEN CITY = 'Boston' THEN (Quantity_Ordered * Price_Each)END), 2) AS Boston,
              ROUND(SUM(CASE WHEN CITY = 'Seattle' THEN (Quantity_Ordered * Price_Each)END), 2) AS Seattle,
              ROUND(SUM(CASE WHEN CITY = 'Austin' THEN (Quantity_Ordered * Price_Each)END), 2) AS Austin,
              ROUND(SUM(CASE WHEN CITY = 'Atlanta' THEN (Quantity_Ordered * Price_Each)END), 2) AS Atlanta,
              ROUND(SUM(CASE WHEN CITY = 'New York City' THEN (Quantity_Ordered * Price_Each)END), 2) AS New_York_City,
              ROUND(SUM(CASE WHEN CITY = 'Los Angeles' THEN (Quantity_Ordered * Price_Each)END), 2) AS Los_Angeles,
              ROUND(SUM(CASE WHEN CITY = 'Dallas' THEN (Quantity_Ordered * Price_Each)END), 2) AS Dallas,
              ROUND(SUM(CASE WHEN CITY IS NULL THEN (Quantity_Ordered * Price_Each)END), 2) AS No_Address
FROM MONTHLY_SALES
GROUP BY MONTH;

--TOTAL REVENUE BY CITY


WITH REVENUE AS (
SELECT MONTH,CITY,
ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_January_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_February_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_March_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_April_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_May_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_June_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_July_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_August_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_September_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_October_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_November_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,ROUND(SUM (Quantity_Ordered * Price_Each), 2) AS REV_PER_CITY
FROM Sales_December_2019
GROUP BY CITY, MONTH
)
SELECT *,
		DENSE_RANK() OVER (PARTITION BY MONTH ORDER BY REV_PER_CITY) AS REVENUE_RANKING
FROM REVENUE;



-- WHAT IS THE TOTAL ORDER BY CITY

WITH  ORDERS  AS (
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_January_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_February_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_March_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_April_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_May_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_June_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_July_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_August_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_September_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_October_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_November_2019
GROUP BY CITY, MONTH
UNION ALL
SELECT MONTH,CITY,
COUNT(Order_ID) AS NO_OF_ORDERS
FROM Sales_December_2019
GROUP BY CITY, MONTH
)
SELECT *,
		DENSE_RANK() OVER (PARTITION BY MONTH ORDER BY NO_OF_ORDERS) AS ORDER_RANKING
FROM ORDERS;